### ISSUE TITLE
控制台报警告Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "show" 

### ISSUE THREAD

**Issue by chenjiaj** [jiaochunxiao/vue-picker#1]
首先感谢你写了这个插件，让我节约了很多时间写弹出插件和移动端选择器插件。现在遇到控制到报警告的问题，请问是否应该删除Popup.vue中hidePopup、cancelPopup、confirmPopup中修改this.show的代码，这句话貌似会导致报子组件修改父组件的警告

**Comment by jiaochunxiao** [comment]
这个问题，请参看另外一个仓库vue-popup，在那边已经做了修改，稍后会同步到vue-picker仓库，多谢

**Comment by jiaochunxiao** [comment]
已修复，多谢。
